// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGa0A-T0lKXwar8x8Z6c8mhKFl6FxxbQ',
    appId: '1:993635914958:web:b95cd1c3ca836fc3042c9f',
    messagingSenderId: '993635914958',
    projectId: 'se7ety-4f4b0',
    authDomain: 'se7ety-4f4b0.firebaseapp.com',
    storageBucket: 'se7ety-4f4b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDgJkIeL-bmNHLnH7AMq0DUUfesqaEPbU',
    appId: '1:993635914958:android:aaf2518372dd1637042c9f',
    messagingSenderId: '993635914958',
    projectId: 'se7ety-4f4b0',
    storageBucket: 'se7ety-4f4b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7S0ZuH3ONOWqK0kWZSWPX_xzVxyO4nY',
    appId: '1:993635914958:ios:63343ab286eea915042c9f',
    messagingSenderId: '993635914958',
    projectId: 'se7ety-4f4b0',
    storageBucket: 'se7ety-4f4b0.firebasestorage.app',
    iosBundleId: 'com.example.se7ety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7S0ZuH3ONOWqK0kWZSWPX_xzVxyO4nY',
    appId: '1:993635914958:ios:63343ab286eea915042c9f',
    messagingSenderId: '993635914958',
    projectId: 'se7ety-4f4b0',
    storageBucket: 'se7ety-4f4b0.firebasestorage.app',
    iosBundleId: 'com.example.se7ety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcGa0A-T0lKXwar8x8Z6c8mhKFl6FxxbQ',
    appId: '1:993635914958:web:ff5a2976f1ba6e7d042c9f',
    messagingSenderId: '993635914958',
    projectId: 'se7ety-4f4b0',
    authDomain: 'se7ety-4f4b0.firebaseapp.com',
    storageBucket: 'se7ety-4f4b0.firebasestorage.app',
  );
}
